declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'
  type Icon = FC<SVGProps<SVGSVGElement>>
  export const Target: Icon
  export const Brain: Icon
  export const BookOpen: Icon
  export const Zap: Icon
  export const Clock: Icon
  export const BarChart3: Icon
  export const Flame: Icon
  export const Calendar: Icon
  export const TrendingUp: Icon
  export const Award: Icon
  export const Coffee: Icon
  export const Play: Icon
  export const Pause: Icon
  export const Check: Icon
export const CheckCircle: Icon
export const Plus: Icon
export const Settings: Icon
export const X: Icon
export const CloudRain: Icon
export const Radio: Icon
export const Keyboard: Icon
export const ArrowLeft: Icon
export const Trash2: Icon
export const Sliders: Icon
export const Volume2: Icon
export const Database: Icon
  export const Sparkles: Icon
  export const ChevronLeft: Icon
  export const ChevronDown: Icon
  export const ChevronUp: Icon
  export const Moon: Icon
  export const Wind: Icon
  export const Timer: Icon
  export const Sun: Icon
  export const Layers: Icon
  export const GraduationCap: Icon
  export const Edit3: Icon
  export const Search: Icon
  export const Save: Icon
  export const FileText: Icon
  export const Heart: Icon
  export const AlertCircle: Icon
  export const Lock: Icon
  export const ChevronRight: Icon
  export const RefreshCw: Icon
  export const FileUp: Icon
  export const Bookmark: Icon
}

